config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :courses do
    collection do
      get ':customize', {
        to: 'courses#customize',
        constraints: ->(request) { Course.where(url: request[:customize]).any? }
      }
    end
  end

  resources :orders, only: [:index]

  mount ApiRoot => ApiRoot::PREFIX

  root to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

# 使用者權限
class Ability
  include CanCan::Ability

  def initialize(user)
    cannot :manage, :all

    can :read, Course
    can :read, Order, student: user

    return unless user.role == 'admin'

    can :manage, Course, user: user
  end
end

app/models/api_access_token.rb
# frozen_string_literal: true

# API Token
class ApiAccessToken < ApplicationRecord
  belongs_to :user

  before_create :generate_keys

  private

  def generate_keys
    loop do
      self.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')

      break unless ApiAccessToken.where(key: key).any?
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :students, through: :orders, source: :student

  validates :title, :currency, :course_type, :expiration_period, presence: true
  validates :is_launched, inclusion: { in: [true, false] }
  validates :price, numericality: { greater_than_or_equal_to: 0, message: '金額必須大於等於 %{count}' }

  scope :is_available, -> { where(is_launched: true) }
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :student, class_name: 'User', foreign_key: 'user_id'
  belongs_to :lesson, class_name: 'Course', foreign_key: 'course_id'

  validates :expired_at, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses
  has_many :orders
  has_many :lessons, through: :orders, source: :lesson
  has_many :tokens, class_name: 'ApiAccessToken'

  after_create do
    tokens.create
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Controller 底層
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[role name])
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

# 課程
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :user_find_course, only: [:show]
  before_action :admin_find_course, only: %i[edit update destroy]

  load_and_authorize_resource

  def index
    @courses = Course.accessible_by(current_ability, :manage)
  end

  def show; end

  def customize
    @course = Course.find_by(url: params[:customize])

    render :show
  end

  def new
    @course = current_user.courses.new
  end

  def create
    @course = current_user.courses.new(course_params)

    if @course.save
      redirect_to courses_path, notice: '課程建立成功！'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: '課程更新成功！'
    else
      render :edit
    end
  end

  def destroy
    @course&.destroy

    redirect_to courses_path, notice: '課程已刪除！'
  end

  private

  def admin_find_course
    @course = Course.accessible_by(current_ability, :manage).find_by(id: params[:id])
  end

  def user_find_course
    @course = Course.accessible_by(current_ability, :read).find_by(id: params[:id])
  end

  def course_params
    params.require(:course).permit(
      :title,
      :url,
      :course_type,
      :expiration_period,
      :currency,
      :price,
      :description,
      :is_launched
    )
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# 首頁
class HomeController < ApplicationController
  def index
    @courses = Course.is_available
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# 訂單
class OrdersController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    @orders = current_user.orders.accessible_by(current_ability)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
# frozen_string_literal: true

# 課程 Helper
module CourseHelper
  CURRENCY_LIST = [
    { id: 1, code: 'TWD', name: '新台幣', symbol: '$' },
    { id: 2, code: 'HKD', name: '港元', symbol: '$' },
    { id: 3, code: 'USD', name: '美元', symbol: '$' },
    { id: 4, code: 'JPY', name: '日圓', symbol: '¥' }
  ].freeze

  COURSE_TYPE = [
    { id: 1, code: 'english', name: '英文' },
    { id: 2, code: 'math', name: '數學' },
    { id: 3, code: 'chinese', name: '國文' }
  ].freeze

  def currency_options
    CURRENCY_LIST.map { |currency| ["#{currency[:name]}（#{currency[:symbol]}）", currency[:code]] }
  end

  def course_type_options
    COURSE_TYPE.map { |type| [type[:name], type[:code]] }
  end

  def expiration_period_options
    (1..31).map { |day| ["#{day} 天", day] }
  end

  def url_for_course(course)
    course.url.present? ? "/courses/#{course.url}" : course_path(course)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

# 使用者 Helper
module UserHelper
  ROLE_LIST =
    [
      { id: 1, code: 'user', name: '訪客' },
      { id: 2, code: 'admin', name: '管理員' }
    ].freeze

  def user_role_options
    ROLE_LIST.map { |role| ["我是#{role[:name]}", role[:code]] }
  end

  def user_role_name
    ROLE_LIST.find { |role| role[:code] == current_user.role }[:name]
  end
end

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-12 pb-3">
    <div class="card shadow">
      <div class="card-body">
        <%= form_for(course) do |f| %>
          <div class="row mb-3">
            <div class="col-md-12">
              <%= f.label :title, '標題', class: 'form-label' %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-8">
              <%= f.label :url, '自訂網址', class: 'form-label' %>
              <div class="input-group">
                <span class="input-group-text"><%= URI.join(root_url, 'courses/').to_s %></span>
                <%= f.text_field :url, class: 'form-control' %>
              </div>
            </div>
            <div class="col-md-4">
              <%= f.label :course_type, '類型', class: 'form-label' %>
              <%= f.select :course_type, course_type_options, {}, class: 'form-select' %>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-6">
              <%= f.label :expiration_period, '效期', class: 'form-label' %>
              <%= f.select :expiration_period, expiration_period_options, {}, class: 'form-select' %>
            </div>
            <div class="col-md-6">
              <%= f.label :price, '售價', class: 'form-label' %>
              <div class="input-group">
                <%= f.select :currency, currency_options, { include_blank: '幣別' }, class: 'form-select' %>
                <%= f.text_field :price, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-12">
              <%= f.label :description, '描述', class: 'form-label' %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-12">
              <div class="form-check">
                <%= f.check_box :is_launched, class: 'form-check-input' %>
                <%= f.label :is_launched, '是否上架', class: 'form-check-label' %>
              </div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-12 d-grid">
              <%= f.submit '儲存', class: 'btn btn-secondary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="row">
  <div class="col-md-12 pt-3">
    <h2>修改課程</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<%= render 'form', course: @course %>
<div class="row">
  <div class="col-md-12 pb-3">
    <%= link_to '返回課程列表頁', courses_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-md-6">
    <section class="h-100 p-5 bg-dark text-white rounded-3">
      <h2><%= current_user&.name %>您好！</h2>
      <h5>您的身份是 <%= user_role_name %></h5>
    </section>
  </div>
  <div class="col-md-6">
    <section class="h-100 p-5 bg-light border rounded-3">
      <h2>還沒開課嗎？</h2>
      <p><%= Faker::Lorem.paragraph %></p>
      <%= link_to('打造獨一無二的課程去！', new_course_path, class: 'btn btn-secondary') %>
    </section>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pt-5">
    <h3>課程列表</h3>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<% if @courses.present? %>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
    <% @courses.each do |course| %>
      <div class="col">
        <div class="card shadow">
          <img src="https://picsum.photos/seed/<%= course.title %>/300/200">
          <div class="card-body">
            <div class="course-title d-flex justify-content-between">
              <h5><%= course.title %></h5>
              <h5><%= "$ #{course.price.to_i}" %></h5>
            </div>
            <p class="card-text"><%= course.description %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to(edit_course_path(course), class: 'btn btn-sm btn-outline-dark') do %>
                  編輯 <i class="fa-solid fa-pen"></i>
                <% end %>
                <%= link_to(course_path(course), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: "確認刪除?" }) do %>
                  刪除 <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </div>
              <small class="text-muted"><%= "By #{course.user.name}" if course.user.name.present? %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12 pb-3">
      <span>目前尚無課程</span>
    </div>
  </div>
<% end %>

app/views/courses/new.html.erb
<div class="row">
  <div class="col-md-12 pt-3">
    <h2>建立課程</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<%= render 'form', course: @course %>
<div class="row">
  <div class="col-md-12 pb-3">
    <%= link_to '返回課程列表頁', courses_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-md-2 pb-5"></div>
  <div class="col-md-8 pb-5">
    <div class="card shadow">
      <img src="https://picsum.photos/seed/<%= @course.title %>/800/600">
      <div class="card-body">
        <div class="course-title d-flex justify-content-between">
          <h5><%= @course.title %></h5>
          <h5><%= "$ #{@course.price.to_i}" %></h5>
        </div>
        <p class="card-text"><%= @course.description %></p>
        <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted"><%= "By #{@course.user.name}" if @course.user.name.present? %></small>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2 pb-5"></div>
</div>
<div class="row">
  <div class="col-md-12 pb-3 text-center">
    <%= link_to '返回首頁', root_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12 pt-3">
    <h2>所有課程</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<% if @courses.present? %>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
    <% @courses.each do |course| %>
      <div class="col">
        <div class="card shadow">
          <img src="https://picsum.photos/seed/<%= course.title %>/300/200">
          <div class="card-body">
            <div class="course-title d-flex justify-content-between">
              <h5><%= course.title %></h5>
              <h5><%= "$ #{course.price.to_i}" %></h5>
            </div>
            <p class="card-text"><%= course.description %></p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted"><%= "By #{course.user.name}" if course.user.name.present? %></small>
              <div class="btn-group">
                <%= link_to(url_for_course(course), class: 'btn btn-sm btn-outline-dark') do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
                <%= link_to('#', class: 'btn btn-sm btn-outline-dark', name: 'buy', id: "buy_course_#{course.id}", data: { id: course.id }) do %>
                  <i class="fa-solid fa-cart-shopping"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12 pb-3">
      <span>目前尚無課程</span>
    </div>
  </div>
<% end %>

<script>
  $(document).on('turbolinks:load',function(){
    $('a[name="buy"]').click(function(e){
      e.preventDefault();

      this_button_id = $(e.currentTarget).data('id');

      $.ajax({
        url: `/api/v1/courses/${this_button_id}/buy`,
        type: 'POST',
        data: { token: "<%= current_user&.tokens&.first&.key %>" },
        success: function(){
          alert('購買成功！');
        },
        error: function(xhr) {
          let res = JSON.parse(xhr.responseText);
          alert(res.error.message);
        }
      });
    });
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hao 教室</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5804dc9206.js" crossorigin="anonymous"></script>
  </head>

  <body class=" bg-secondary" style="--bs-bg-opacity: .05;">
    <%= render 'shared/navbar' %>
    <%= render "shared/flash" if notice || alert %> 
    <main class="container-md mt-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-md-12 pt-3">
    <h2>訂購紀錄</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12 pb-3">
    <hr/>
  </div>
</div>
<div class="row mb-5">
  <div class="col-md-12">
    <div id="orderList"></div>
  </div>
</div>
<div class="row mb-3">
  <div class="col-md-12">
    <%= link_to '返回首頁', root_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<script>
  $(document).on('turbolinks:load',function(){
    $.ajax({
      url: '/api/v1/orders?token=<%= current_user&.tokens&.first.key %>',
      type: 'GET',
      success: function(res){
        let orders = res.orders;

        if (orders.length > 0) {
          dataCard(orders);
        } else {
          let text = document.createElement('h5');
          text.textContent = '目前尚無訂單資料';

          let list = document.getElementById('orderList');

          list.appendChild(text);
        }
      }
    });
  })

  function dataCard(orders) {
    let row, col, card, header, headerText, body, title, titleText, img, text;

    orders.forEach(order => {
      card = document.createElement('div');
      card.classList.add('card');

      header = document.createElement('div');
      header.classList.add('card-header');

      headerText = document.createElement('h5');
      headerText.textContent = `#${order.id}`;

      row = document.createElement('div');
      row.classList.add('row');
      row.classList.add('g-0');

      col = document.createElement('div');
      col.classList.add('col-md-4');

      img = document.createElement('img');
      img.src = `https://picsum.photos/seed/${order.title}/300/200`;
      img.classList.add('img-fluid');

      col.appendChild(img);
      row.appendChild(col);
      
      col = document.createElement('div');
      col.classList.add('col-md-8');

      body = document.createElement('div');
      body.classList.add('card-body');

      title = document.createElement('div');
      title.classList.add('card-title');

      titleText = document.createElement('h3');
      titleText.classList.add('mb-3');
      titleText.textContent = order.title;

      title.appendChild(titleText);
      body.appendChild(title);

      text = document.createElement('p');
      text.classList.add('card-text');
      text.textContent = `訂單金額: ${order.total}`;
      body.appendChild(text);

      text = document.createElement('p');
      text.classList.add('card-text');
      text.textContent = `課程有效期限: ${order.expired_at} 止`;
      body.appendChild(text);

      col.appendChild(body);
      row.appendChild(col);

      header.appendChild(headerText);
      card.appendChild(header);
      card.appendChild(row);

      row = document.createElement('div');
      row.classList.add('row');
      row.classList.add('mb-3');
      
      col = document.createElement('div');
      col.classList.add('col-md-12');

      col.appendChild(card);
      row.appendChild(col);

      document.getElementById('orderList').appendChild(row);
    });
  }
</script>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow py-3">
    <div class="container-md">
      <%= link_to('Hao 教室', root_path, class: 'navbar-brand') %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to('訂購紀錄', orders_path, class: 'nav-link') %>
        </li>
      </ul>
        <form class="d-flex">
          <% if user_signed_in? %>
            <%= link_to('登出', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark me-3') %>
            <%= link_to('管理後台', courses_path, class: 'btn btn-dark') if can?(:manage, Course) %>
          <% else %>
            <%= link_to('登入', new_user_session_path, class: 'btn btn-outline-dark me-3') %>
            <%= link_to('註冊', new_user_registration_path, class: 'btn btn-dark') %>
          <% end %>
        </form>
    </div>
  </nav>
</header>